#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'chef-client'
cookbook 'apt'
cookbook 'apache2', '>= 1.0.0'
cookbook 'git'
cookbook 'sqlite'
cookbook 'mysql'
cookbook 'rails'
cookbook 'passenger_apache2'
cookbook 'rvm'
cookbook 'redmine', :git => 'https://github.com/agencyrepublic/chef-redmine'