maintainer        "LLC Express 42"
maintainer_email  "info@express42.com"
license           "Copyright"
description       "Deploy Strano Application"
version           "0.0.1"
depends           "sudo"
depends           "rvm"
depends           "lvm"
